### ISSUE TITLE
OpenCore选择系统后黑屏

### ISSUE THREAD

**Issue by ZongXR** [vicjax/z7-ct7na-Hackintosh#2]
使用dmg安装时，引导进OpenCore能正常显示，但是选择mac系统后黑屏

**Comment by vicjax** [comment]
建议添加-v参数查看具体代码
________________________________
发件人: zong.xiangrui ***@***.***>
发送时间: 2024年10月23日 13:57
收件人: vicjax/z7-ct7na-Hackintosh ***@***.***>
抄送: Subscribed ***@***.***>
主题: [vicjax/z7-ct7na-Hackintosh] OpenCore选择系统后黑屏 (Issue #2)


使用dmg安装时，引导进OpenCore能正常显示，但是选择mac系统后黑屏

―
